#!/usr/bin/env python3
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Project Dev Tools.')

    #Run django command
    parser.add_argument('hello', type=str, help='Run django command')

    args = parser.parse_args()

    if args.hello == 'hello':
        print('Hello World!')
    else:
        parser.print_help()